import type { QuizQuestion } from './question-bank';

export const GRADE4B_QUESTION_BANK: QuizQuestion[] = [
  {
    id: 'grade4b-mandarin-001',
    grade: 'grade4b',
    subject: '國語',
    prompt: '「月亮像一盞小燈，照亮夜晚的路。」這句用了哪一種修辭？',
    options: ['譬喻', '排比', '設問', '反覆'],
    answerIndex: 0,
    explanation: '把月亮比成小燈，是譬喻的寫法。',
  },
  {
    id: 'grade4b-mandarin-002',
    grade: 'grade4b',
    subject: '國語',
    prompt: '「小河唱著歌，慢慢流向遠方。」這句用了哪一種修辭？',
    options: ['誇飾', '擬人', '頂真', '引用'],
    answerIndex: 1,
    explanation: '小河不會真的唱歌，作者把它寫得像人一樣。',
  },
  {
    id: 'grade4b-mandarin-003',
    grade: 'grade4b',
    subject: '國語',
    prompt: '哪一個成語最適合形容「做一件事得到兩種好處」？',
    options: ['一舉兩得', '三心二意', '畫蛇添足', '井底之蛙'],
    answerIndex: 0,
    explanation: '一舉兩得表示一次行動得到兩種收穫。',
  },
  {
    id: 'grade4b-mandarin-004',
    grade: 'grade4b',
    subject: '國語',
    prompt: '「他做事常常半途而廢。」句中的「半途而廢」意思最接近哪一個？',
    options: ['很早完成', '做到一半就停止', '反覆檢查', '重新開始'],
    answerIndex: 1,
    explanation: '半途而廢表示事情還沒完成就放棄。',
  },
  {
    id: 'grade4b-mandarin-005',
    grade: 'grade4b',
    subject: '國語',
    prompt: '「他（　）會彈鋼琴，（　）會拉小提琴。」括號最適合填入哪一組關聯詞？',
    options: ['因為／所以', '雖然／但是', '不但／而且', '如果／就'],
    answerIndex: 2,
    explanation: '句子在說兩項本領都會，適合用「不但／而且」。',
  },
  {
    id: 'grade4b-mandarin-006',
    grade: 'grade4b',
    subject: '國語',
    prompt: '下列哪一句標點最正確？',
    options: ['媽媽問：「你吃飯了嗎？」', '媽媽問：「你吃飯了嗎」。', '媽媽問，你吃飯了嗎？', '媽媽問「你吃飯了嗎？」。'],
    answerIndex: 0,
    explanation: '直接說出的問句要放在引號中，問號也放在引號內。',
  },
  {
    id: 'grade4b-mandarin-007',
    grade: 'grade4b',
    subject: '國語',
    prompt: '「悠閒」的意思最接近哪一個？',
    options: ['慌張忙亂', '輕鬆自在', '又累又餓', '非常生氣'],
    answerIndex: 1,
    explanation: '悠閒表示心情放鬆、行動不急。',
  },
  {
    id: 'grade4b-mandarin-008',
    grade: 'grade4b',
    subject: '國語',
    prompt: '「謙虛」的相反詞最接近哪一個？',
    options: ['勤勞', '勇敢', '驕傲', '安靜'],
    answerIndex: 2,
    explanation: '謙虛是不自滿；驕傲常表示自以為了不起。',
  },
  {
    id: 'grade4b-mandarin-009',
    grade: 'grade4b',
    subject: '國語',
    prompt: '閱讀短文：「小廷每天整理書包，考前也列出複習表。」這段主要想表現小廷怎樣？',
    options: ['愛睡覺', '有計畫', '喜歡吵鬧', '害怕上學'],
    answerIndex: 1,
    explanation: '整理書包和列複習表都表示做事有計畫。',
  },
  {
    id: 'grade4b-mandarin-010',
    grade: 'grade4b',
    subject: '國語',
    prompt: '哪一個句子最適合作為「保護校園植物」文章的結尾？',
    options: ['昨天操場有很多人。', '讓我們一起愛護植物，讓校園更美麗。', '鉛筆盒裡有橡皮擦。', '我今天吃了麵包。'],
    answerIndex: 1,
    explanation: '結尾適合收束主題並提出行動或感想。',
  },
  {
    id: 'grade4b-mandarin-011',
    grade: 'grade4b',
    subject: '國語',
    prompt: '「這場比賽非常（　）烈，兩隊都全力以赴。」括號中最適合填哪個字？',
    options: ['激', '竟', '鏡', '境'],
    answerIndex: 0,
    explanation: '比賽很緊張、很有競爭感，可以說「激烈」。',
  },
  {
    id: 'grade4b-mandarin-012',
    grade: 'grade4b',
    subject: '國語',
    prompt: '下列哪一個詞語用字正確？',
    options: ['分辨方向', '分辯方向', '花瓣方向', '辦別方向'],
    answerIndex: 0,
    explanation: '分辨表示區分、判斷，辨的字形最合適。',
  },
  {
    id: 'grade4b-mandarin-013',
    grade: 'grade4b',
    subject: '國語',
    prompt: '「校慶當天，家長和同學絡繹不絕地走進校園。」句中的「絡繹不絕」表示什麼？',
    options: ['完全沒有來', '連續不斷', '走得很慢', '只來一個人'],
    answerIndex: 1,
    explanation: '絡繹不絕表示人或車馬前後連續，沒有中斷。',
  },
  {
    id: 'grade4b-mandarin-014',
    grade: 'grade4b',
    subject: '國語',
    prompt: '「弟弟把功課寫完以後，才去打球。」這句主要表達哪一件事先發生？',
    options: ['去打球', '寫完功課', '買球鞋', '整理球場'],
    answerIndex: 1,
    explanation: '句中說寫完功課以後才去打球，所以寫功課先發生。',
  },
  {
    id: 'grade4b-mandarin-015',
    grade: 'grade4b',
    subject: '國語',
    prompt: '哪一個句子有排比的效果？',
    options: ['風吹過樹梢。', '我們要勤讀書、常運動、懂禮貌。', '他今天帶了一把傘。', '天空出現一道彩虹。'],
    answerIndex: 1,
    explanation: '三個結構相近的短語並列，形成排比效果。',
  },
  {
    id: 'grade4b-mandarin-016',
    grade: 'grade4b',
    subject: '國語',
    prompt: '下列哪一句語意最完整、最通順？',
    options: ['因為下雨，所以比賽延期。', '因為下雨，比賽。', '所以延期因為下雨。', '比賽因為所以下雨延期。'],
    answerIndex: 0,
    explanation: '「因為下雨，所以比賽延期。」前後原因和結果都完整。',
  },
  {
    id: 'grade4b-mandarin-017',
    grade: 'grade4b',
    subject: '國語',
    prompt: '閱讀短文：「阿芳先查資料，再和同學討論，最後完成海報。」最適合的標題是哪一個？',
    options: ['一張海報的完成', '雨天的操場', '好吃的早餐', '迷路的小狗'],
    answerIndex: 0,
    explanation: '短文重點是完成海報的過程。',
  },
  {
    id: 'grade4b-mandarin-018',
    grade: 'grade4b',
    subject: '國語',
    prompt: '「他跑得像風一樣快。」這句是在強調什麼？',
    options: ['跑得很慢', '跑得很快', '風很安靜', '他沒有跑步'],
    answerIndex: 1,
    explanation: '用「像風一樣」來強調速度很快。',
  },
  {
    id: 'grade4b-mandarin-019',
    grade: 'grade4b',
    subject: '國語',
    prompt: '哪一個詞語最適合接在「珍惜」後面？',
    options: ['時間', '聲音很藍', '昨天跑步', '如果桌子'],
    answerIndex: 0,
    explanation: '常說珍惜時間、珍惜資源、珍惜友誼。',
  },
  {
    id: 'grade4b-mandarin-020',
    grade: 'grade4b',
    subject: '國語',
    prompt: '「老師提醒我們：考試時要先看清楚題目。」冒號的作用是什麼？',
    options: ['表示後面有說明或引出內容', '表示句子已經結束', '表示聲音拉長', '表示兩個字相同'],
    answerIndex: 0,
    explanation: '冒號常用來引出後面的說明、話語或列舉內容。',
  },
  {
    id: 'grade4b-english-001',
    grade: 'grade4b',
    subject: '英語',
    prompt: '「現在幾點？」的英文最接近哪一句？',
    options: ['What time is it?', 'Where are you?', 'How old is it?', 'What color is it?'],
    answerIndex: 0,
    explanation: '詢問時間可以說 What time is it?',
  },
  {
    id: 'grade4b-english-002',
    grade: 'grade4b',
    subject: '英語',
    prompt: 'A: What time is it? B: It is seven o\'clock. B 的意思是什麼？',
    options: ['現在七點', '現在星期七', '這是七本書', '我七歲'],
    answerIndex: 0,
    explanation: 'seven o\'clock 表示七點鐘。',
  },
  {
    id: 'grade4b-english-003',
    grade: 'grade4b',
    subject: '英語',
    prompt: '「我星期一有英文課。」英文最適合哪一句？',
    options: ['I have English on Monday.', 'I has English on Monday.', 'I am English Monday.', 'I do Monday English.'],
    answerIndex: 0,
    explanation: 'I 搭配 have，星期幾前常用 on。',
  },
  {
    id: 'grade4b-english-004',
    grade: 'grade4b',
    subject: '英語',
    prompt: 'Which sentence is correct?',
    options: ['She like cats.', 'She likes cats.', 'She liking cats.', 'She are cats.'],
    answerIndex: 1,
    explanation: '主詞 She 搭配一般現在式動詞 likes。',
  },
  {
    id: 'grade4b-english-005',
    grade: 'grade4b',
    subject: '英語',
    prompt: '「你喜歡香蕉嗎？」英文最接近哪一句？',
    options: ['Do you like bananas?', 'Are you banana?', 'Can bananas you?', 'What banana is it?'],
    answerIndex: 0,
    explanation: '詢問喜好可以用 Do you like ...?',
  },
  {
    id: 'grade4b-english-006',
    grade: 'grade4b',
    subject: '英語',
    prompt: 'A: Do you like milk? B: Yes, I do. B 的意思是什麼？',
    options: ['是的，我喜歡。', '不，我不喜歡。', '我在學校。', '這是牛奶。'],
    answerIndex: 0,
    explanation: 'Yes, I do. 是對 Do you...? 的肯定回答。',
  },
  {
    id: 'grade4b-english-007',
    grade: 'grade4b',
    subject: '英語',
    prompt: '「圖書館」的英文是哪一個？',
    options: ['library', 'kitchen', 'bathroom', 'playground'],
    answerIndex: 0,
    explanation: 'library 是圖書館。',
  },
  {
    id: 'grade4b-english-008',
    grade: 'grade4b',
    subject: '英語',
    prompt: '「操場」的英文是哪一個？',
    options: ['playground', 'bedroom', 'restaurant', 'market'],
    answerIndex: 0,
    explanation: 'playground 是操場或遊樂場。',
  },
  {
    id: 'grade4b-english-009',
    grade: 'grade4b',
    subject: '英語',
    prompt: 'A: Where is the cat? B: It is under the table. 貓在哪裡？',
    options: ['桌子下面', '桌子上面', '門旁邊', '盒子裡面'],
    answerIndex: 0,
    explanation: 'under the table 表示在桌子下面。',
  },
  {
    id: 'grade4b-english-010',
    grade: 'grade4b',
    subject: '英語',
    prompt: '「在盒子裡」的英文是哪一個？',
    options: ['in the box', 'on the box', 'under the box', 'next the box'],
    answerIndex: 0,
    explanation: 'in 表示在裡面。',
  },
  {
    id: 'grade4b-english-011',
    grade: 'grade4b',
    subject: '英語',
    prompt: '「晴朗的」英文是哪一個？',
    options: ['sunny', 'rainy', 'windy', 'cloudy'],
    answerIndex: 0,
    explanation: 'sunny 表示晴朗的。',
  },
  {
    id: 'grade4b-english-012',
    grade: 'grade4b',
    subject: '英語',
    prompt: 'A: How is the weather? B: It is rainy. 天氣如何？',
    options: ['下雨', '晴朗', '很熱', '下雪'],
    answerIndex: 0,
    explanation: 'rainy 表示下雨的。',
  },
  {
    id: 'grade4b-english-013',
    grade: 'grade4b',
    subject: '英語',
    prompt: '「我會游泳。」英文最接近哪一句？',
    options: ['I can swim.', 'I am swim.', 'I swim can.', 'I do can swimming.'],
    answerIndex: 0,
    explanation: '表達能力可以用 can 加原形動詞。',
  },
  {
    id: 'grade4b-english-014',
    grade: 'grade4b',
    subject: '英語',
    prompt: 'Which one is a month?',
    options: ['April', 'Friday', 'summer', 'breakfast'],
    answerIndex: 0,
    explanation: 'April 是月份，表示四月。',
  },
  {
    id: 'grade4b-english-015',
    grade: 'grade4b',
    subject: '英語',
    prompt: '「星期三」的英文是哪一個？',
    options: ['Wednesday', 'Weekend', 'Weather', 'Window'],
    answerIndex: 0,
    explanation: 'Wednesday 是星期三。',
  },
  {
    id: 'grade4b-english-016',
    grade: 'grade4b',
    subject: '英語',
    prompt: 'A: How many pencils do you have? B: I have twelve pencils. 有幾枝鉛筆？',
    options: ['12 枝', '10 枝', '2 枝', '20 枝'],
    answerIndex: 0,
    explanation: 'twelve 表示十二。',
  },
  {
    id: 'grade4b-english-017',
    grade: 'grade4b',
    subject: '英語',
    prompt: '「她正在讀書。」英文最接近哪一句？',
    options: ['She is reading.', 'She are read.', 'She reading is.', 'She reads yesterday.'],
    answerIndex: 0,
    explanation: '正在做某事可用 be 動詞加 V-ing。',
  },
  {
    id: 'grade4b-english-018',
    grade: 'grade4b',
    subject: '英語',
    prompt: '哪一句可以回答「What do you want?」',
    options: ['I want some juice.', 'I am ten years old.', 'It is Monday.', 'He is my brother.'],
    answerIndex: 0,
    explanation: 'What do you want? 在問想要什麼，可以回答 I want...',
  },
  {
    id: 'grade4b-english-019',
    grade: 'grade4b',
    subject: '英語',
    prompt: '「早餐」的英文是哪一個？',
    options: ['breakfast', 'basket', 'beautiful', 'between'],
    answerIndex: 0,
    explanation: 'breakfast 是早餐。',
  },
  {
    id: 'grade4b-english-020',
    grade: 'grade4b',
    subject: '英語',
    prompt: 'Which sentence is polite when asking for water?',
    options: ['May I have some water?', 'Give water now!', 'Water me fast.', 'No water you.'],
    answerIndex: 0,
    explanation: 'May I have...? 是有禮貌的請求句型。',
  },
  {
    id: 'grade4b-math-001',
    grade: 'grade4b',
    subject: '數學',
    prompt: '3.6 + 2.45 = ?',
    options: ['5.05', '6.05', '5.95', '6.15'],
    answerIndex: 1,
    explanation: '3.60 + 2.45 = 6.05。',
  },
  {
    id: 'grade4b-math-002',
    grade: 'grade4b',
    subject: '數學',
    prompt: '8 - 3.27 = ?',
    options: ['4.63', '4.73', '5.73', '5.83'],
    answerIndex: 1,
    explanation: '8.00 - 3.27 = 4.73。',
  },
  {
    id: 'grade4b-math-003',
    grade: 'grade4b',
    subject: '數學',
    prompt: '1/4 + 2/4 = ?',
    options: ['3/4', '3/8', '2/8', '1/2'],
    answerIndex: 0,
    explanation: '同分母分數相加，分母不變，分子相加得到 3/4。',
  },
  {
    id: 'grade4b-math-004',
    grade: 'grade4b',
    subject: '數學',
    prompt: '5/6 - 2/6 = ?',
    options: ['3/6', '7/6', '3/12', '2/3'],
    answerIndex: 0,
    explanation: '同分母分數相減，分母不變，5 - 2 = 3。',
  },
  {
    id: 'grade4b-math-005',
    grade: 'grade4b',
    subject: '數學',
    prompt: '下列哪一個分數和 1/2 一樣大？',
    options: ['2/4', '1/3', '3/5', '4/6'],
    answerIndex: 0,
    explanation: '1/2 的分子分母同乘 2，可得到 2/4。',
  },
  {
    id: 'grade4b-math-006',
    grade: 'grade4b',
    subject: '數學',
    prompt: '一個長方形長 9 公分、寬 6 公分，面積是多少？',
    options: ['15 平方公分', '30 平方公分', '54 平方公分', '60 平方公分'],
    answerIndex: 2,
    explanation: '長方形面積 = 長 × 寬 = 9 × 6 = 54。',
  },
  {
    id: 'grade4b-math-007',
    grade: 'grade4b',
    subject: '數學',
    prompt: '一個正方形邊長 7 公分，周長是多少？',
    options: ['14 公分', '21 公分', '28 公分', '49 公分'],
    answerIndex: 2,
    explanation: '正方形周長 = 邊長 × 4 = 7 × 4 = 28。',
  },
  {
    id: 'grade4b-math-008',
    grade: 'grade4b',
    subject: '數學',
    prompt: '一個角是 90 度，這個角叫做什麼角？',
    options: ['銳角', '直角', '鈍角', '平角'],
    answerIndex: 1,
    explanation: '90 度的角是直角。',
  },
  {
    id: 'grade4b-math-009',
    grade: 'grade4b',
    subject: '數學',
    prompt: '一個角比 90 度小，這個角叫做什麼角？',
    options: ['銳角', '直角', '鈍角', '周角'],
    answerIndex: 0,
    explanation: '小於 90 度的角是銳角。',
  },
  {
    id: 'grade4b-math-010',
    grade: 'grade4b',
    subject: '數學',
    prompt: '三角形的三個內角總和是多少？',
    options: ['90 度', '180 度', '270 度', '360 度'],
    answerIndex: 1,
    explanation: '三角形的三內角和是 180 度。',
  },
  {
    id: 'grade4b-math-011',
    grade: 'grade4b',
    subject: '數學',
    prompt: '480 ÷ 6 = ?',
    options: ['60', '70', '80', '90'],
    answerIndex: 2,
    explanation: '48 ÷ 6 = 8，所以 480 ÷ 6 = 80。',
  },
  {
    id: 'grade4b-math-012',
    grade: 'grade4b',
    subject: '數學',
    prompt: '125 × 8 = ?',
    options: ['900', '1000', '1100', '1200'],
    answerIndex: 1,
    explanation: '125 × 8 = 1000。',
  },
  {
    id: 'grade4b-math-013',
    grade: 'grade4b',
    subject: '數學',
    prompt: '2 公尺 35 公分等於幾公分？',
    options: ['235 公分', '2035 公分', '20035 公分', '37 公分'],
    answerIndex: 0,
    explanation: '2 公尺是 200 公分，再加 35 公分是 235 公分。',
  },
  {
    id: 'grade4b-math-014',
    grade: 'grade4b',
    subject: '數學',
    prompt: '3 公斤 250 公克等於幾公克？',
    options: ['325 公克', '3025 公克', '3250 公克', '3500 公克'],
    answerIndex: 2,
    explanation: '3 公斤是 3000 公克，再加 250 公克是 3250 公克。',
  },
  {
    id: 'grade4b-math-015',
    grade: 'grade4b',
    subject: '數學',
    prompt: '一列火車 8:35 出發，9:20 到站，花了多久？',
    options: ['35 分鐘', '45 分鐘', '55 分鐘', '1 小時 45 分鐘'],
    answerIndex: 1,
    explanation: '8:35 到 9:00 是 25 分鐘，9:00 到 9:20 是 20 分鐘，共 45 分鐘。',
  },
  {
    id: 'grade4b-math-016',
    grade: 'grade4b',
    subject: '數學',
    prompt: '某班最喜歡的水果統計：蘋果 8 人、香蕉 12 人、葡萄 6 人。最多人喜歡哪一種？',
    options: ['蘋果', '香蕉', '葡萄', '一樣多'],
    answerIndex: 1,
    explanation: '12 最大，所以最多人喜歡香蕉。',
  },
  {
    id: 'grade4b-math-017',
    grade: 'grade4b',
    subject: '數學',
    prompt: '把 96 顆糖果平分給 8 人，每人幾顆？',
    options: ['10 顆', '11 顆', '12 顆', '14 顆'],
    answerIndex: 2,
    explanation: '96 ÷ 8 = 12。',
  },
  {
    id: 'grade4b-math-018',
    grade: 'grade4b',
    subject: '數學',
    prompt: '0.7 和 0.65 哪一個比較大？',
    options: ['0.7', '0.65', '一樣大', '無法比較'],
    answerIndex: 0,
    explanation: '0.7 = 0.70，0.70 比 0.65 大。',
  },
  {
    id: 'grade4b-math-019',
    grade: 'grade4b',
    subject: '數學',
    prompt: '一個長方形周長 30 公分，長 9 公分，寬是多少？',
    options: ['5 公分', '6 公分', '12 公分', '21 公分'],
    answerIndex: 1,
    explanation: '長方形周長 = (長 + 寬) × 2，30 ÷ 2 = 15，15 - 9 = 6。',
  },
  {
    id: 'grade4b-math-020',
    grade: 'grade4b',
    subject: '數學',
    prompt: '一盒色鉛筆 48 元，買 6 盒要多少元？',
    options: ['248 元', '268 元', '288 元', '308 元'],
    answerIndex: 2,
    explanation: '48 × 6 = 288。',
  },
];
